### ISSUE TITLE
Some SD card don't work

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/pelion-ready-example#11]
When running the application, you may see:

```
Start Simple Mbed Cloud Client
Failed to mount FAT file system, reformatting...
Failed to reformat FAT file system
```

This may be caused by the SD not working properly, or the SD driver not being compatible with this brand.

Does work:
- Sandisk 8GB HC1
- Sandisk 2GB
- Trascend 2GB
- Kingston 16GB HC4

May not work:
- Kingston 8GB HC4 (should be fixed by https://github.com/ARMmbed/sd-driver/commit/3e23227be6696a4ec44fe1390a4bc95b347c7761)

**Comment by amq** [comment]
Possibly related: https://github.com/ARMmbed/mbed-os/issues/6374
