### ISSUE TITLE
Use default RoT in developer mode to avoid invalidating credentials from ext storage

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/pelion-ready-example#26]
This is a UX enhancement.

In MCC 1.4.1, there is a Hardcoded RoT when compiled in Developer-mode. This change will allow a user to reflash the application without invalidating the old credentials due to RoT change. 

Before this change, the RoT stored in SOTP was erased everytime the application binary was reflashed causing the endpoint to change its ID.

**Comment by screamerbg** [comment]
@MarceloSalazar Can we close this? Is this still relevant?

**Comment by MarceloSalazar** [comment]
It's still relevant. We should try to implement it at some point.
