### ISSUE TITLE
GR-LYCHEE doesn't work as is

### ISSUE THREAD

**Issue by coisme** [ARMmbed/pelion-ready-example#51]
In the current revision a5d2cf40f3709c856a1cc65226895552a78c4831, GR-LYCHEE doesn't connect to network out of box.

I needed to some modification on Wi-Fi driver to make GR-LYCHEE connect to network.
* Remove this line to disable the default driver
https://github.com/ARMmbed/pelion-ready-example/blob/a5d2cf40f3709c856a1cc65226895552a78c4831/mbed_app.json#L206
* Added another driver
```mbed add https://github.com/d-kato/esp32-driver```

Related information is here:
https://os.mbed.com/questions/84006/Will-the-ESP32-library-be-supported-in-M/

**Comment by toyowata** [comment]
@coisme You can find the GR-LYCHEE and GR-PEACH example here: https://os.mbed.com/teams/Renesas/code/pelion-example-common/

**Comment by coisme** [comment]
Got it. I thought this project worked for all the Pelion Ready boards. Close the issue.
