### ISSUE TITLE
pelion client failed at initialization (error code = 16)

### ISSUE THREAD

**Issue by chuanga** [ARMmbed/pelion-ready-example#53]
Tested on WISE-1530 with external SD card reader and got the following error messages:
*********  
Initializing Pelion Device Management Client...
Pelion Client initialization failed (16)
*********
It looks like it's caused by the latest change to mbed-os.
Need to replace specific filesystem declaration with get_default_instance() API call instead.

FileSystem *fs = FileSystem::get_default_instance();

Once I replaced the fs declaration with the above, PDMC starts to work again

**Comment by screamerbg** [comment]
@chuanga Is this still relevant?

**Comment by MarceloSalazar** [comment]
Closing - please reopen if continues to be a problem.
