### ISSUE TITLE
Mbed-printf can decrease flash usage by 15K

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/pelion-ready-example#58]
But it does require building with a separate profile. E.g.:

```
$ mbed add mbed-printf
$ mbed compile --profile=./mbed-printf/profiles/release.json

Total Static RAM memory (data + bss): 72024(+0) bytes
Total Flash memory (text + data): 372019(-15274) bytes
```

So not sure whether it belongs in the Pelion ready example. @marcuschangarm What's the status on mainlining mbed-printf ?

**Comment by marcuschangarm** [comment]
There is no interest in Mbed OS to mainline _minimal_-printf.

**Comment by janjongboom** [comment]
@marcuschangarm Ah, it's renamed now. Why not actually? 15K flash is a lot.

**Comment by marcuschangarm** [comment]
It's not 100% compliant with the specs.

**Comment by janjongboom** [comment]
@marcuschangarm Yes, but why not as a feature that you can enable?

**Comment by marcuschangarm** [comment]
That's an excellent question! 😕

**Comment by janjongboom** [comment]
@bulislaw What do you think? ^

**Comment by bulislaw** [comment]
There's a preq to use minimal-printf in Mbed OS: ISGDEVPREQ-1365
